version: "3"
services:
  fluree:
    image: fluree/ledger:1.0.0-beta19
    restart: always
    ports:
      - 8090:8090
    environment:
      - FDB_CONSENSUS_TYPE=in-memory
      - FDB_STORAGE_TYPE=memory
    volumes:
      - ./docker-data/fluree:/var/lib/fluree
